# -*- coding: utf-8 -*-
"""GNN Fault Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdZQ_YgNxTbdvqgJUQEXOghF006ehyPq
"""

# Install PyTorch Geometric
!pip install torch-geometric
!pip install torch torchvision

# Import libraries
import torch
import torch.nn.functional as F
from torch_geometric.data import Data

print("PyTorch version:", torch.__version__)
print("Libraries imported successfully!")

# Step 1: Component Vocabulary — One Hot Encoding ke liye
COMPONENT_VOCAB = {
    "battery": 0,
    "power_supply": 1,
    "resistor": 2,
    "capacitor": 3,
    "inductor": 4,
    "led": 5,
    "diode": 6,
    "zener_diode": 7,
    "transistor": 8,
    "npn_transistor": 9,
    "pnp_transistor": 10,
    "mosfet": 11,
    "op_amp": 12,
    "motor": 13,
    "switch": 14,
    "ground": 15
}

NUM_CLASSES = len(COMPONENT_VOCAB)  # 16

def encode_node(component_name: str) -> torch.Tensor:
    """
    Convert component name to One Hot Encoded vector.
    Unknown components get a zero vector.
    """
    idx = COMPONENT_VOCAB.get(component_name.lower(), -1)

    if idx == -1:
        # Unknown component — zero vector
        return torch.zeros(NUM_CLASSES)

    return F.one_hot(
        torch.tensor(idx),
        num_classes=NUM_CLASSES
    ).float()

# Test
print("battery encoding:")
print(encode_node("battery"))
print("\nresistor encoding:")
print(encode_node("resistor"))
print("\nled encoding:")
print(encode_node("led"))

# Step 2: Circuit JSON ko Graph object mein convert karna

def circuit_to_graph(circuit_json: dict) -> Data:
    """
    Circuit JSON ko PyTorch Geometric Data object mein convert karta hai.

    Input:
        circuit_json: dict with components and connections
    Output:
        PyG Data object (x, edge_index, y)
    """
    components  = [c.lower() for c in circuit_json.get("components", [])]
    connections = circuit_json.get("connections", [])
    label       = circuit_json.get("label", 0)  # 0=Valid, 1=Short, 2=Floating

    # ── Node Features (One Hot Encoding) ──────────────────────
    node_features = torch.stack([encode_node(c) for c in components])

    # ── Edge Index ────────────────────────────────────────────
    edge_src = []  # from
    edge_dst = []  # to

    for connection in connections:
        # Parse "battery -> resistor -> led"
        if "->" in connection:
            nodes = [n.strip().lower() for n in connection.split("->")]
        elif "--" in connection:
            nodes = [n.strip().lower() for n in connection.split("--")]
        else:
            continue

        for i in range(len(nodes) - 1):
            src = nodes[i]
            dst = nodes[i + 1]

            # Component ka index dhundo
            if src in components and dst in components:
                edge_src.append(components.index(src))
                edge_dst.append(components.index(dst))

    # Edge index tensor
    if edge_src:
        edge_index = torch.tensor([edge_src, edge_dst], dtype=torch.long)
    else:
        edge_index = torch.zeros((2, 0), dtype=torch.long)

    # ── Label ─────────────────────────────────────────────────
    y = torch.tensor([label], dtype=torch.long)

    return Data(x=node_features, edge_index=edge_index, y=y)


# ── Test ──────────────────────────────────────────────────────

# Test 1 — Valid circuit
circuit1 = {
    "circuit_name": "Valid LED Circuit",
    "components":   ["battery", "resistor", "led"],
    "connections":  ["battery -> resistor -> led"],
    "label":        0  # Valid
}

# Test 2 — Short circuit
circuit2 = {
    "circuit_name": "Short Circuit",
    "components":   ["battery", "ground"],
    "connections":  ["battery -> ground"],
    "label":        1  # Short Circuit
}

# Test 3 — Floating component
circuit3 = {
    "circuit_name": "Floating Motor",
    "components":   ["battery", "resistor", "led", "motor"],
    "connections":  ["battery -> resistor -> led"],
    "label":        2  # Floating
}

for circuit in [circuit1, circuit2, circuit3]:
    graph = circuit_to_graph(circuit)
    print(f"\nCircuit: {circuit['circuit_name']}")
    print(f"  Nodes : {graph.x.shape}  → {graph.x.shape[0]} components, {graph.x.shape[1]} features each")
    print(f"  Edges : {graph.edge_index.shape} → {graph.edge_index.shape[1]} connections")
    print(f"  Label : {graph.y.item()} ({'Valid' if graph.y==0 else 'Short Circuit' if graph.y==1 else 'Floating'})")

# Step 3: Training Dataset banana

dataset = [
    # ── Valid Circuits ──────────────────────────────────────
    {
        "circuit_name": "Valid LED Circuit",
        "components":   ["battery", "resistor", "led"],
        "connections":  ["battery -> resistor -> led"],
        "label":        0
    },
    {
        "circuit_name": "Valid Motor Circuit",
        "components":   ["battery", "switch", "motor"],
        "connections":  ["battery -> switch -> motor"],
        "label":        0
    },
    {
        "circuit_name": "Valid RC Circuit",
        "components":   ["battery", "resistor", "capacitor"],
        "connections":  ["battery -> resistor -> capacitor"],
        "label":        0
    },
    {
        "circuit_name": "Valid NPN Circuit",
        "components":   ["battery", "npn_transistor", "led"],
        "connections":  ["battery -> npn_transistor -> led"],
        "label":        0
    },
    {
        "circuit_name": "Valid Diode Circuit",
        "components":   ["battery", "resistor", "diode"],
        "connections":  ["battery -> resistor -> diode"],
        "label":        0
    },

    # ── Short Circuit ───────────────────────────────────────
    {
        "circuit_name": "Short Circuit - Direct",
        "components":   ["battery", "ground"],
        "connections":  ["battery -> ground"],
        "label":        1
    },
    {
        "circuit_name": "Short Circuit - Wire",
        "components":   ["battery", "ground"],
        "connections":  ["battery -> ground"],
        "label":        1
    },
    {
        "circuit_name": "Short Circuit - Capacitor",
        "components":   ["battery", "capacitor", "ground"],
        "connections":  ["battery -> capacitor -> ground"],
        "label":        1
    },
    {
        "circuit_name": "Short Circuit - LED bypass",
        "components":   ["battery", "led", "ground"],
        "connections":  ["battery -> led -> ground"],
        "label":        1
    },
    {
        "circuit_name": "Short Circuit - Switch",
        "components":   ["battery", "switch", "ground"],
        "connections":  ["battery -> switch -> ground"],
        "label":        1
    },

    # ── Floating Component ──────────────────────────────────
    {
        "circuit_name": "Floating Motor",
        "components":   ["battery", "resistor", "led", "motor"],
        "connections":  ["battery -> resistor -> led"],
        "label":        2
    },
    {
        "circuit_name": "Floating Capacitor",
        "components":   ["battery", "resistor", "led", "capacitor"],
        "connections":  ["battery -> resistor -> led"],
        "label":        2
    },
    {
        "circuit_name": "Floating LED",
        "components":   ["battery", "resistor", "motor", "led"],
        "connections":  ["battery -> resistor -> motor"],
        "label":        2
    },
    {
        "circuit_name": "Floating Transistor",
        "components":   ["battery", "resistor", "led", "transistor"],
        "connections":  ["battery -> resistor -> led"],
        "label":        2
    },
    {
        "circuit_name": "Floating Diode",
        "components":   ["battery", "resistor", "motor", "diode"],
        "connections":  ["battery -> resistor -> motor"],
        "label":        2
    },
]

# Circuit JSON ko graph objects mein convert karo
graph_dataset = [circuit_to_graph(c) for c in dataset]

# Summary
print(f"Total circuits in dataset : {len(graph_dataset)}")
print(f"Valid circuits            : {sum(1 for c in dataset if c['label'] == 0)}")
print(f"Short circuits            : {sum(1 for c in dataset if c['label'] == 1)}")
print(f"Floating components       : {sum(1 for c in dataset if c['label'] == 2)}")
print(f"\nEach node has {graph_dataset[0].x.shape[1]} features (One Hot Encoded)")

# Step 4: GNN Model banana
from torch_geometric.nn import GCNConv, global_mean_pool
import torch.nn as nn

class CircuitGNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        """
        input_dim  = node features size (16 — one hot vocab size)
        hidden_dim = internal layer size (32)
        output_dim = number of classes (3 — Valid, Short, Floating)
        """
        super(CircuitGNN, self).__init__()

        # ── Graph Convolution Layers ───────────────────────────
        # Layer 1: har node apne direct neighbors se seekhta hai
        self.conv1 = GCNConv(input_dim, hidden_dim)

        # Layer 2: 2 hops door tak dekhta hai
        self.conv2 = GCNConv(hidden_dim, hidden_dim)

        # ── Classifier ────────────────────────────────────────
        # Graph level prediction ke liye
        self.classifier = nn.Linear(hidden_dim, output_dim)

        # Dropout — overfitting rokne ke liye
        self.dropout = nn.Dropout(p=0.3)

    def forward(self, data):
        x          = data.x           # Node features
        edge_index = data.edge_index  # Connections
        batch      = data.batch if hasattr(data, 'batch') and data.batch is not None \
                     else torch.zeros(x.size(0), dtype=torch.long)

        # ── Step 1: Message Passing ────────────────────────────
        # Har node apne neighbors ki info leta hai
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.dropout(x)

        # ── Step 2: Deeper understanding ──────────────────────
        x = self.conv2(x, edge_index)
        x = F.relu(x)

        # ── Step 3: Graph level representation ────────────────
        # Sare nodes ka average leke poore graph ko ek vector mein compress karo
        x = global_mean_pool(x, batch)

        # ── Step 4: Classification ─────────────────────────────
        x = self.classifier(x)

        return x


# Model banao
model = CircuitGNN(
    input_dim  = NUM_CLASSES,  # 16 — vocab size
    hidden_dim = 32,
    output_dim = 3             # Valid, Short Circuit, Floating
)

print(model)
print(f"\nTotal parameters: {sum(p.numel() for p in model.parameters())}")

# Step 5: Data Generator — 600+ circuits automatically banana
import random

# Component pools
POWER_SOURCES    = ["battery", "power_supply"]
RESISTORS        = ["resistor"]
LEDS             = ["led", "diode", "zener_diode"]
TRANSISTORS      = ["transistor", "npn_transistor", "pnp_transistor", "mosfet"]
OUTPUTS          = ["led", "motor", "diode", "buzzer"]
ALL_COMPONENTS   = list(COMPONENT_VOCAB.keys())

def generate_valid_circuits(n=200):
    """200 valid circuits generate karo"""
    circuits = []

    for _ in range(n):
        power     = random.choice(POWER_SOURCES)
        mid       = random.choice(RESISTORS + TRANSISTORS)
        output    = random.choice(["led", "motor", "diode", "capacitor"])

        # Kabhi kabhi extra component add karo
        if random.random() > 0.5:
            components  = [power, mid, output]
            connections = [f"{power} -> {mid} -> {output}"]
        else:
            extra       = random.choice(RESISTORS)
            components  = [power, mid, extra, output]
            connections = [f"{power} -> {mid} -> {extra} -> {output}"]

        circuits.append({
            "components":  components,
            "connections": connections,
            "label":       0  # Valid
        })

    return circuits


def generate_short_circuits(n=200):
    """200 short circuits generate karo"""
    circuits = []

    for _ in range(n):
        power = random.choice(POWER_SOURCES)

        # 3 types of short circuits
        short_type = random.randint(1, 3)

        if short_type == 1:
            # Direct short — battery -> ground
            components  = [power, "ground"]
            connections = [f"{power} -> ground"]

        elif short_type == 2:
            # Wire through short — battery -> wire -> ground
            mid         = random.choice(["switch", "capacitor", "inductor"])
            components  = [power, mid, "ground"]
            connections = [f"{power} -> {mid} -> ground"]

        else:
            # Multi node short
            n1          = random.choice(["led", "diode", "capacitor"])
            n2          = random.choice(["switch", "inductor"])
            components  = [power, n1, n2, "ground"]
            connections = [f"{power} -> {n1} -> {n2} -> ground"]

        circuits.append({
            "components":  components,
            "connections": connections,
            "label":       1  # Short Circuit
        })

    return circuits


def generate_floating_circuits(n=200):
    """200 floating component circuits generate karo"""
    circuits = []

    for _ in range(n):
        power      = random.choice(POWER_SOURCES)
        resistor   = "resistor"
        output     = random.choice(["led", "motor", "diode"])

        # Yeh component connected nahi hoga — floating
        floating   = random.choice(["motor", "capacitor", "transistor",
                                    "npn_transistor", "inductor", "op_amp"])

        components  = [power, resistor, output, floating]
        connections = [f"{power} -> {resistor} -> {output}"]
        # floating component connections mein nahi hai intentionally

        circuits.append({
            "components":  components,
            "connections": connections,
            "label":       2  # Floating
        })

    return circuits


# Generate all data
valid_data    = generate_valid_circuits(200)
short_data    = generate_short_circuits(200)
floating_data = generate_floating_circuits(200)

# Combine aur shuffle
all_data = valid_data + short_data + floating_data
random.shuffle(all_data)

# Graph objects mein convert karo
full_dataset = [circuit_to_graph(c) for c in all_data]

print(f"Total dataset size : {len(full_dataset)}")
print(f"Valid circuits     : {len(valid_data)}")
print(f"Short circuits     : {len(short_data)}")
print(f"Floating circuits  : {len(floating_data)}")

# Step 6: Dataset ko Train aur Test mein split karo

from torch_geometric.loader import DataLoader

# 80% training, 20% testing
split       = int(len(full_dataset) * 0.8)
train_data  = full_dataset[:split]
test_data   = full_dataset[split:]

# DataLoader — model ko batch mein data deta hai
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader  = DataLoader(test_data,  batch_size=32, shuffle=False)

print(f"Total dataset  : {len(full_dataset)}")
print(f"Training data  : {len(train_data)}")
print(f"Testing data   : {len(test_data)}")
print(f"Batch size     : 32")
print(f"Training batches : {len(train_loader)}")
print(f"Testing batches  : {len(test_loader)}")

# Step 7: Model Training

import torch.optim as optim

# Device setup — GPU available hai tu GPU use karo
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Model ko device pe bhejo
model = model.to(device)

# Optimizer — model ke weights update karta hai
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Loss function — model kitna galat hai yeh measure karta hai
criterion = nn.CrossEntropyLoss()

# Training function
def train(epoch):
    model.train()
    total_loss    = 0
    correct       = 0
    total_samples = 0

    for batch in train_loader:
        batch = batch.to(device)

        # Step 1: Purani calculations clear karo
        optimizer.zero_grad()

        # Step 2: Forward pass — model prediction karo
        output = model(batch)

        # Step 3: Loss calculate karo
        loss = criterion(output, batch.y)

        # Step 4: Backward pass — galtiyan seekho
        loss.backward()

        # Step 5: Weights update karo
        optimizer.step()

        # Accuracy track karo
        pred           = output.argmax(dim=1)
        correct        += (pred == batch.y).sum().item()
        total_samples  += batch.y.size(0)
        total_loss     += loss.item()

    accuracy = correct / total_samples * 100
    avg_loss = total_loss / len(train_loader)
    return avg_loss, accuracy


# Testing function
def test():
    model.eval()
    correct       = 0
    total_samples = 0

    with torch.no_grad():
        for batch in test_loader:
            batch  = batch.to(device)
            output = model(batch)
            pred   = output.argmax(dim=1)
            correct       += (pred == batch.y).sum().item()
            total_samples += batch.y.size(0)

    return correct / total_samples * 100


# ── Training shuru karo ───────────────────────────────────────
print("\nTraining shuru ho rahi hai...\n")
print(f"{'Epoch':<8} {'Loss':<12} {'Train Acc':<15} {'Test Acc':<10}")
print("-" * 45)

EPOCHS = 50

for epoch in range(1, EPOCHS + 1):
    train_loss, train_acc = train(epoch)
    test_acc              = test()

    if epoch % 5 == 0:
        print(f"{epoch:<8} {train_loss:<12.4f} {train_acc:<15.2f} {test_acc:<10.2f}")

print("\nTraining complete! ✅")

# Step 8: Model Save karna

import os
from google.colab import drive

# Google Drive mount karo — file permanently save rahegi
drive.mount('/content/drive')

# Save path
save_dir  = '/content/drive/MyDrive/CircuitMind_GNN'
os.makedirs(save_dir, exist_ok=True)

# Model weights save karo
model_path = os.path.join(save_dir, 'circuit_gnn.pt')
torch.save({
    'model_state_dict':     model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'vocab':                COMPONENT_VOCAB,
    'num_classes':          NUM_CLASSES,
    'epoch':                EPOCHS,
}, model_path)

print(f"✅ Model saved to: {model_path}")

# Step 9: Real Prediction — Fixed Version

def predict_circuit(circuit_json: dict) -> str:
    model.eval()

    # Circuit ko graph mein convert karo
    graph = circuit_to_graph(circuit_json)

    # Sab tensors ek hi device pe bhejo
    graph.x          = graph.x.to(device)
    graph.edge_index = graph.edge_index.to(device)

    # Batch manually banao — ek graph hai toh sab zeros
    graph.batch = torch.zeros(
        graph.x.size(0),
        dtype=torch.long
    ).to(device)  # ← yahan .to(device) zaroori tha — yahi error thi

    # Prediction karo
    with torch.no_grad():
        output     = model(graph)
        prediction = output.argmax(dim=1).item()
        confidence = F.softmax(output, dim=1).max().item() * 100

    # Label decode karo
    labels = {
        0: "✅ Valid Circuit",
        1: "❌ Short Circuit",
        2: "⚠️  Floating Component"
    }

    result = labels[prediction]

    print(f"Circuit    : {circuit_json.get('circuit_name', 'Unknown')}")
    print(f"Prediction : {result}")
    print(f"Confidence : {confidence:.2f}%")
    print("-" * 40)

    return result


# ── Test Cases ────────────────────────────────────────────────
predict_circuit({
    "circuit_name": "New Valid Circuit",
    "components":   ["power_supply", "resistor", "led"],
    "connections":  ["power_supply -> resistor -> led"]
})

predict_circuit({
    "circuit_name": "New Short Circuit",
    "components":   ["battery", "inductor", "ground"],
    "connections":  ["battery -> inductor -> ground"]
})

predict_circuit({
    "circuit_name": "New Floating Circuit",
    "components":   ["battery", "resistor", "motor", "op_amp"],
    "connections":  ["battery -> resistor -> motor"]
})

predict_circuit({
    "circuit_name": "Complex Valid Circuit",
    "components":   ["battery", "resistor", "npn_transistor", "led"],
    "connections":  ["battery -> resistor -> npn_transistor -> led"]
})

predict_circuit({
    "circuit_name": "My Custom Circuit",
    "components":   ["battery", "switch", "resistor", "motor"],
    "connections":  ["battery -> switch -> resistor -> motor"]
})

# Step 10: Confusion Matrix — detailed analysis

from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Test data pe sari predictions lo
all_preds  = []
all_labels = []

model.eval()
with torch.no_grad():
    for batch in test_loader:
        # Sab tensors device pe bhejo
        batch.x          = batch.x.to(device)
        batch.edge_index = batch.edge_index.to(device)
        batch.y          = batch.y.to(device)
        batch.batch      = batch.batch.to(device)

        output = model(batch)
        preds  = output.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(batch.y.cpu().numpy())

# Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)

# Plot
plt.figure(figsize=(8, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Valid', 'Short Circuit', 'Floating'],
    yticklabels=['Valid', 'Short Circuit', 'Floating']
)
plt.title('CircuitMind GNN — Confusion Matrix')
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/CircuitMind_GNN/confusion_matrix.png')
plt.show()

# Detailed Report
print("\nClassification Report:")
print(classification_report(
    all_labels,
    all_preds,
    target_names=['Valid', 'Short Circuit', 'Floating']
))

